### ISSUE TITLE
AttributeError: 'QStyleHints' object has no attribute 'colorSchemeChanged'

### ISSUE THREAD

**Issue by marvin8** [seird/gotify-tray#33]
Just upgraded to 0.5.0 and tried to restart gotify-try and am getting an AttributeError now.

Here's the stack trace i get:
```
Traceback (most recent call last):
  File "/home/mark/.local/bin/gotify-tray", line 8, in <module>
    sys.exit(main())
  File "/home/mark/.local/pipx/venvs/gotify-tray/lib/python3.10/site-packages/gotify_tray/__main__.py", line 9, in main
    start_gui()
  File "/home/mark/.local/pipx/venvs/gotify-tray/lib/python3.10/site-packages/gotify_tray/gui/MainApplication.py", line 402, in start_gui
    app.init_ui()
  File "/home/mark/.local/pipx/venvs/gotify-tray/lib/python3.10/site-packages/gotify_tray/gui/MainApplication.py", line 95, in init_ui
    self.link_callbacks()
  File "/home/mark/.local/pipx/venvs/gotify-tray/lib/python3.10/site-packages/gotify_tray/gui/MainApplication.py", line 359, in link_callbacks
    self.styleHints().colorSchemeChanged.connect(lambda _: self.theme_change_requested_callback(settings.value("theme", type=str)))
AttributeError: 'QStyleHints' object has no attribute 'colorSchemeChanged'
```

I am on Manjaro using XFCE / I3

**Comment by seird** [comment]
can you check the pyqt6 version with `pip show pyqt6` or whatever the equivalent is in pipx? It should be 6.5.0, the callback doesn't exist in previous versions.

**Comment by marvin8** [comment]
Looks like I am on an earlier version... 
```
Name: PyQt6
Version: 6.4.0
Summary: Python bindings for the Qt cross platform application toolkit
Home-page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Location: /home/mark/.local/pipx/venvs/gotify-tray/lib/python3.10/site-packages
Requires: PyQt6-Qt6, PyQt6-sip
Required-by: gotify-tray
```

**Comment by marvin8** [comment]
I've uninstalled gotify-tray with pipx and then re-installed it again.

That installed PyQt6.5.0 and it's working again... Thanks for your help
